export { Home } from './Home'
export { About } from './About'
export { Projects } from './Projects'
export { Blog } from './Blog'
export { CommunityWall } from './CommunityWalll'
export { Stats } from './Stats'
export { Resume } from './Resume'